### ISSUE TITLE
Allow commenting on a card

### ISSUE THREAD

**Issue by geolessel** [geolessel/trello-cli#10]
I really don't know the best way to go about this. I think the way I imagine this working for now is kinda like how git interrupts itself, opens your `$EDITOR`, then receives the output of the editor. I have no idea how to make that work, though. I played around with sending signals to the trello app but couldn't get very far.

For reference, I think this is where git handles all that:
https://github.com/git/git/blob/53f9a3e157dbbc901a02ac2c73346d375e24978c/editor.c

Any insight, @seven1m?

**Comment by seven1m** [comment]
There's a really neat curses-based Python app called "bbj" that embeds your editor of choice in a frame inside the app. I don't know exactly how it works, but I'm thinking we could figure it out!

https://github.com/desvox/bbj

![bbj](https://user-images.githubusercontent.com/669/45045239-ff6fb180-b037-11e8-8c4b-31abe162e384.gif)

**Comment by geolessel** [comment]
wut

**Comment by geolessel** [comment]
Completed by #14
