### ISSUE TITLE
bew install faild

### ISSUE THREAD

**Issue by AntonVLA** [geolessel/trello-cli#27]
In src/label_select_window.cr:8:5

 8 | super(x: NCurses.maxx / 4, y: NCurses.maxy / 4, width: NCurses.maxx / 2, height: NCurses.maxy / 2) do |win|
     ^----
Error: no overload matches 'OptionSelectWindow#initialize', x: Float64, y: Float64, width: Float64, height: Float64

Overloads are:
 - OptionSelectWindow#initialize(x : Int32, y : Int32, height : Int32, width : Int32)
 - OptionSelectWindow#initialize(x : Int32, y : Int32, height : Int32, width : Int32, &block)
make: *** [make] Error 1

**Comment by jlmcgehee21** [comment]
I just encountered this. I suspect it is because Brew seems to be pinned to Crystal `0.35.0`, and this was written with `0.26.0`.

I've not touched Crystal myself, but seeing if I can do anything on the brew side to get my install working.

**Comment by Oppen** [comment]
This is fixed in HEAD.

**Comment by augustebaum** [comment]
I just had this exact issue (Brew is pinned to Crystal `0.35.1_1` now).
